name: dolphyn
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  web3dart: ^1.2.3
  get: ^3.24.0
  web_socket_channel: ^1.1.0
  hex: ^0.1.2
  flutter_secure_storage: ^3.3.5
  google_fonts: ^1.1.1
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  build_runner: ^1.10.1
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
  json_serializable: ^3.4.1
  build_verify: ^1.1.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
